- name: backend
  hosts: backend
  become: yes
  tasks: 
  - name: installing nodejs
    ansible.builtin.package:
     name: nodejs
     state: present

  - name: checking user
    ansible.builtin.command: id expense
    ignore_errors: true
    register: error

  - name: watching user
    ansible.builtin.debug:
     msg: "show: {{error}}"

  - name: adding user
    ansible.builtin.command: useradd expense
    when: error.rc != 0