- name: backend
  hosts: backend
  become: yes
  tasks: 
    - name: Disable Node.js module
      ansible.builtin.dnf:
        name: nodejs
        state: absent
        disable_gpg_check: yes

    - name: Enable Node.js version 20 module
      ansible.builtin.dnf:
        name: "@nodejs:20"
        state: present
        enable: yes
        disable_gpg_check: yes

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Check if user 'expense' exists
      ansible.builtin.user:
        name: expense
        state: present
        update_password: on_create
        createhome: yes
      ignore_errors: true
      register: error

    - name: Add user 'expense' if not exists
      ansible.builtin.user:
        name: expense
        state: present
      when: error.rc != 0

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download backend zip file
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: Unzip backend package into /app
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
        creates: /app/package.json

    - name: Install npm
      ansible.builtin.package:
        name: npm
        state: present

    - name: Copy backend.service to systemd
      ansible.builtin.copy:
        src: /home/ec2-user/expense-ansible/backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: Load MySQL schema
      ansible.builtin.mysql_db:
        name: backend
        state: import
        target: /app/schema/backend.sql
        login_host: database.the4teen.info
        login_user: root
        login_password: 'ExpenseApp@1'

    - name: Reload systemd daemon and start backend service
      ansible.builtin.systemd:
        name: backend
        state: started
        enabled: yes
