- name: creating databse
  hosts: database
  become: yes
  tasks:
  - name: installing mysql
    yum:
     name: mysql-server
     state: present
  
  - name: enable and start
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes